apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-service
  template:
    metadata:
      labels:
        app: resources-service
    spec:
      containers:
      - name: resources-service
        image: localhost:5000/resources-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: k8s-program
spec:
  selector:
    app: resources-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
