apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-vars
  namespace: k8s-program
data:
  RESOURCES_MS_NAME: resources-ms
  RESOURCES_MS_PORT: "8080"
  SONGS_MS_NAME: songs-ms
  SONGS_MS_PORT: "8081"
  EUREKA_URI: localhost
  ENABLE_EUREKA_CLIENT: "false"
  RESOURCES_DB_HOST: resources-db.k8s-program.svc.cluster.local
  RESOURCES_DB_PORT: "5432"
  SONGS_DB_HOST: songs-db.k8s-program.svc.cluster.local
  SONGS_DB_PORT: "5432"
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres