apiVersion: v1
kind: Service
metadata:
  name: resources-db
  namespace: k8s-program
spec:
  type: ClusterIP  # Restrict external access
  selector:
    app: resources-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432