apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resources-db
  namespace: k8s-program
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-db
  serviceName: resources-db
  template:
    metadata:
      labels:
        app: resources-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
          volumeMounts:
            - name: resources-db-storage
              mountPath: /var/lib/postgresql/data
            - name: db-init-script
              mountPath: /docker-entrypoint-initdb.d/ # Directory for auto-init scripts
      volumes:
        - name: db-init-script
          configMap:
            name: db-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: resources-db-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path