apiVersion: v1
kind: Service
metadata:
  name: songs-db
  namespace: k8s-program
spec:
  type: ClusterIP
  selector:
    app: songs-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432