apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.resources.db.name }}"
  namespace: "{{ .Values.global.namespace }}"
spec:
  replicas: {{ .Values.resources.db.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.resources.db.name }}"
  serviceName: "{{ .Values.resources.db.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.resources.db.name }}"
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.resources.db.image }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: resources-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: resources-password
            - name: POSTGRES_DB
              value: "{{ .Values.resources.db.databaseName }}"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: db-init-scripts
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: db-init-scripts
          configMap:
            name: db-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.resources.db.storageSize }}
        storageClassName: {{ .Values.resources.db.storageClassName }}