apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  resources-username: {{ .Values.dbCredentials.resources.username | b64enc }}
  resources-password: {{ .Values.dbCredentials.resources.password | b64enc }}
  songs-username: {{ .Values.dbCredentials.songs.username | b64enc }}
  songs-password: {{ .Values.dbCredentials.songs.password | b64enc }}