apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.songs.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.songs.service.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.songs.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.songs.service.name }}
    spec:
      containers:
        - name: {{ .Values.songs.service.name }}
          image: {{ .Values.songs.service.image }}
          ports:
            - containerPort: {{ .Values.songs.service.containerPort }}
          env:
            - name: SONGS_DB_HOST
              value: "{{ .Values.songs.db.name }}.{{ .Values.global.namespace }}.svc.cluster.local"
            - name: SONGS_DB_PORT
              value: "5432"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: songs-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: songs-password
